#!/usr/bin/env node
/**
 * Writes the mushaf structure the Flutter app browses offline:
 * flutter_app/assets/quran/structure.json
 *
 * Everything comes from the parsed SOURCE dataset (quran-meta boundaries and
 * the surah metadata quran-json carries) — the same parse the import uses.
 * The file holds no Quranic text at all: only numbers and surah names, so it
 * can ship inside the app regardless of the text licence.
 *
 * Deterministic: the same sources always produce the same bytes, and the
 * quality gate regenerates it and compares.
 */
import { mkdirSync, writeFileSync } from 'node:fs';
import path from 'node:path';
import { parseDataset } from '../src/import/parse.ts';
import { QURAN_JSON_VERSION, QURAN_META_VERSION } from '../src/import/registry.ts';

const dataset = parseDataset([]);

const boundaries = (division: { number: number; start_surah: number; start_ayah: number; end_surah: number; end_ayah: number; start_global_ayah: number; end_global_ayah: number }) => ({
  number: division.number,
  start: { surah: division.start_surah, ayah: division.start_ayah, global: division.start_global_ayah },
  end: { surah: division.end_surah, ayah: division.end_ayah, global: division.end_global_ayah },
});

const surahs = dataset.surahs.map((surah) => {
  const ayahs = dataset.ayahs.filter((ayah) => ayah.surah_number === surah.surah_number);
  const pages = ayahs.map((ayah) => ayah.page_number);
  const juzs = ayahs.map((ayah) => ayah.juz_number);
  const hizbs = ayahs.map((ayah) => ayah.hizb_number);
  return {
    number: surah.surah_number,
    name_ar: surah.name_ar,
    transliteration: surah.name_transliteration,
    revelation_place: surah.revelation_place,
    revelation_order: surah.revelation_order,
    ayah_count: surah.ayah_count,
    start_page: Math.min(...pages),
    end_page: Math.max(...pages),
    start_juz: Math.min(...juzs),
    end_juz: Math.max(...juzs),
    start_hizb: Math.min(...hizbs),
    end_hizb: Math.max(...hizbs),
    manzil: ayahs[0]!.manzil_number,
    ruku_count: new Set(ayahs.map((ayah) => ayah.ruku_number)).size,
    sajdah_count: ayahs.filter((ayah) => ayah.sajdah).length,
    first_global_ayah: ayahs[0]!.global_ayah_number,
  };
});

// Hizbs are the 60 groups of four quarters.
const hizbs = Array.from({ length: 60 }, (_, index) => {
  const number = index + 1;
  const quarters = dataset.rubs.filter((rub) => rub.hizb_number === number);
  const first = quarters[0]!;
  const last = quarters[quarters.length - 1]!;
  return {
    number,
    juz: first.juz_number,
    start: { surah: first.start_surah, ayah: first.start_ayah, global: first.start_global_ayah },
    end: { surah: last.end_surah, ayah: last.end_ayah, global: last.end_global_ayah },
  };
});

const structure = {
  sources: { 'quran-meta': QURAN_META_VERSION, 'quran-json': QURAN_JSON_VERSION },
  note: 'Structure only — no Quranic text. Generated by quran_api/scripts/quran-structure.ts from the source dataset; never edited by hand.',
  totals: {
    surahs: surahs.length,
    ayahs: dataset.ayahs.length,
    juzs: dataset.juzs.length,
    hizbs: hizbs.length,
    rubs: dataset.rubs.length,
    pages: dataset.pages.length,
    manzils: dataset.manzils.length,
    rukus: dataset.rukus.length,
    sajdahs: dataset.ayahs.filter((ayah) => ayah.sajdah).length,
  },
  surahs,
  juzs: dataset.juzs.map(boundaries),
  hizbs,
  rubs: dataset.rubs.map((rub) => ({ ...boundaries(rub), hizb: rub.hizb_number, quarter: rub.quarter, juz: rub.juz_number })),
  pages: dataset.pages.map(boundaries),
  manzils: dataset.manzils.map(boundaries),
  rukus: dataset.rukus.map((ruku) => ({ ...boundaries(ruku), surah: ruku.surah_number })),
  sajdahs: dataset.ayahs
    .filter((ayah) => ayah.sajdah)
    .map((ayah) => ({ surah: ayah.surah_number, ayah: ayah.ayah_number, global: ayah.global_ayah_number, juz: ayah.juz_number, page: ayah.page_number })),
};

const out = path.join(import.meta.dirname, '..', '..', 'flutter_app', 'assets', 'quran');
mkdirSync(out, { recursive: true });
const target = path.join(out, 'structure.json');
writeFileSync(target, `${JSON.stringify(structure)}\n`);
console.log(
  `structure written: ${Object.entries(structure.totals).map(([key, value]) => `${key}=${value}`).join(' ')} → ${path.relative(process.cwd(), target)}`,
);
