/**
 * Per-record data checks. Every one of the 15,961 imported records is checked
 * INDIVIDUALLY against the source file it came from, the hash the database
 * computed, its printed locator, its metadata and the exported dataset.
 * Nothing here writes: the corpus is opened read-only.
 */
import { readFileSync } from 'node:fs';
import { createHash } from 'node:crypto';
import { query } from '../db.ts';
import { contentHash } from '../domain/hash.ts';
import type { Auditor } from './core.ts';

/** The release under audit; override with DATASET= to audit an older one. */
const DATASET = process.env['DATASET'] ?? 'JAMI-KAMIL-1437-V2';

const DATA_DIR = process.env['DATA_DIR'] ?? 'data';
const REPRO = 'npm run audit -- --only=data';
const LOCATOR_VOL = 'ج';
const LOCATOR_PAGE = 'ص';

interface Row {
  id: string;
  raw_text: string;
  content_hash: string;
  volume_number: number | null;
  page_number: number | null;
  source_locator: string | null;
  source_ordinal: number | null;
  dataset_version: string;
  verified: boolean;
  verification_status: string;
  source_locked: boolean;
  matn: string | null;
  isnad: string | null;
  takhrij: string | null;
  grading: string | null;
  hadith_number: string | null;
}

interface VolumeIndex {
  /** every trimmed line of the file, for verbatim membership */
  lines: Set<string>;
  /** trimmed line -> the (volume,page) markers it appears under */
  pages: Map<string, Set<string>>;
  maxPage: number;
  sha256: string;
}

const volumes = new Map<number, VolumeIndex>();
const PAGE_MARKER = new RegExp(`^\\[${LOCATOR_VOL}(\\d+)\\s+${LOCATOR_PAGE}(\\d+)\\]`);

function volumeIndex(volume: number): VolumeIndex {
  const cached = volumes.get(volume);
  if (cached) return cached;
  const file = `${DATA_DIR}/jami-kamil-j${String(volume).padStart(2, '0')}.txt`;
  const buf = readFileSync(file);
  const text = buf.toString('utf8');
  const lines = new Set<string>();
  const pages = new Map<string, Set<string>>();
  let vol = volume;
  let page = 0;
  let maxPage = 0;
  for (const raw of text.split('\n')) {
    const line = raw.replace(/[ \t]+$/, '');
    const marker = PAGE_MARKER.exec(line.trim());
    if (marker) {
      vol = Number(marker[1]);
      page = Number(marker[2]);
      if (page > maxPage) maxPage = page;
      continue;
    }
    if (line.trim() === '') continue;
    // A record line is printed with a bullet prefix; the stored text keeps the
    // wording and drops the bullet, so both forms are indexed.
    for (const form of new Set([line, line.replace(/^\s*[•‣●-]\s*/, '')])) {
      lines.add(form);
      let set = pages.get(form);
      if (!set) { set = new Set<string>(); pages.set(form, set); }
      set.add(`${vol}/${page}`);
    }
  }
  const idx: VolumeIndex = { lines, pages, maxPage, sha256: createHash('sha256').update(buf).digest('hex') };
  volumes.set(volume, idx);
  return idx;
}

/** Characters that must never appear in stored religious text. */
const FORBIDDEN = /[\u0000-\u0008\u000B\u000C\u000E-\u001F\uFFFD]/;
const HTML = /<\/?(p|div|span|br|script|a|b|i)\b/i;
const AI_MARKER =
  /(as an ai|language model|chatgpt|gpt-4|gpt-3|openai|generated by|\bTODO\b|lorem ipsum|placeholder|حديث تجريبي|نص تجريبي)/i;

export async function runDataChecks(audit: Auditor): Promise<void> {
  const rows = await query<Row>(
    `select id, raw_text, content_hash, volume_number, page_number, source_locator,
            source_ordinal, dataset_version, verified, verification_status, source_locked,
            matn, isnad, takhrij, grading, hadith_number
       from corpus.hadiths order by volume_number, page_number, source_ordinal`,
  );

  const exported = new Map<string, Record<string, unknown>>();
  try {
    const jsonl = readFileSync(`exports/${DATASET}.jsonl`, 'utf8');
    for (const line of jsonl.split('\n')) {
      if (!line.trim()) continue;
      const obj = JSON.parse(line) as Record<string, unknown>;
      exported.set(String(obj['id']), obj);
    }
  } catch { /* reported per record below */ }

  const hashSeen = new Map<string, string[]>();
  const rankOnPage = new Map<string, number>();
  let previousOrdinal = 0;
  let previousVolume: number | null = null;

  for (const row of rows) {
    const loc = row.source_locator ?? row.id;
    const vol = row.volume_number;
    const idx = vol ? volumeIndex(vol) : null;
    const storedLines = row.raw_text.split('\n')
      .map((l) => l.replace(/[ \t]+$/, ''))
      .filter((l) => l.trim() !== '');

    // 1. verbatim: every stored line still exists, character for character,
    //    in the volume file it was imported from.
    if (idx) {
      const missing = storedLines.filter((l) => !idx.lines.has(l));
      audit.check(`data.verbatim:${loc}`, 'data.raw_verbatim',
        'stored text exists character-for-character in its source volume file',
        missing.length === 0, {
          severity: 'CRITICAL',
          detail: missing.length
            ? `${missing.length}/${storedLines.length} line(s) absent from volume ${vol}: ${JSON.stringify(missing[0]?.slice(0, 80))}`
            : '',
          where: `${DATA_DIR}/jami-kamil-j${String(vol).padStart(2, '0')}.txt`,
          repro: REPRO,
        });

      // 2. the record sits on the page it claims
      const claimed = `${vol}/${row.page_number}`;
      const first = storedLines[0] ?? '';
      const found = idx.pages.get(first);
      audit.check(`data.page_claim:${loc}`, 'data.page_claim',
        'the record occurs on the volume/page its locator claims',
        Boolean(found && found.has(claimed)), {
          severity: 'HIGH',
          detail: found ? `text occurs on ${[...found].join(', ')} but not on ${claimed}` : 'first line not located in the volume',
          where: 'src/importer/adapters/jami_kamil_shamela.ts',
          repro: REPRO,
        });

      // 3. page within the printed range of that volume
      audit.check(`data.page_range:${loc}`, 'data.metadata',
        'page_number lies inside the printed page range of its volume',
        row.page_number !== null && row.page_number > 0 && row.page_number <= idx.maxPage, {
          severity: 'HIGH',
          detail: `page ${row.page_number} outside 1..${idx.maxPage}`,
          where: 'corpus.hadiths.page_number',
          repro: REPRO,
        });
    } else {
      audit.check(`data.volume_present:${loc}`, 'data.metadata',
        'every record carries the volume it was printed in', false, {
          severity: 'HIGH', detail: 'volume_number is null', where: 'corpus.hadiths.volume_number', repro: REPRO,
        });
    }

    // 4. the database-computed hash equals a fresh hash of the stored text
    audit.check(`data.hash:${loc}`, 'data.hash_integrity',
      'content_hash equals sha256 of the stored text recomputed now',
      row.content_hash === contentHash(row.raw_text), {
        severity: 'CRITICAL',
        detail: `stored ${row.content_hash} vs recomputed ${contentHash(row.raw_text)}`,
        where: 'corpus.hadiths.content_hash (generated column)',
        repro: REPRO,
      });

    // 5. locator is the printed coordinate (volume/page + rank on that page),
    //    never an invented hadith number: this edition prints none.
    const pageKey = `${vol}/${row.page_number}`;
    if (vol !== previousVolume) { previousOrdinal = 0; previousVolume = vol; }
    const rank = (rankOnPage.get(pageKey) ?? 0) + 1;
    rankOnPage.set(pageKey, rank);
    const expectedLocator = `${LOCATOR_VOL}${vol}/${LOCATOR_PAGE}${row.page_number}/#${rank}`;
    audit.check(`data.locator:${loc}`, 'data.locator',
      'source_locator is exactly the printed volume/page coordinate plus its rank on that page',
      row.source_locator === expectedLocator, {
        severity: 'HIGH',
        detail: `locator ${row.source_locator} does not match ${expectedLocator}`,
        where: 'src/importer/adapters/jami_kamil_shamela.ts',
        repro: REPRO,
      });

    // 5b. reading order is strictly increasing, so no record was reordered
    audit.check(`data.ordinal:${loc}`, 'data.locator',
      'source_ordinal increases strictly in printed reading order within its volume',
      row.source_ordinal !== null && row.source_ordinal > previousOrdinal, {
        severity: 'HIGH',
        detail: `ordinal ${row.source_ordinal} does not follow ${previousOrdinal}`,
        where: 'corpus.hadiths.source_ordinal',
        repro: REPRO,
      });
    previousOrdinal = row.source_ordinal ?? previousOrdinal;

    // 5c. this edition prints no hadith numbers, so none may be invented
    audit.check(`data.no_invented_number:${loc}`, 'data.locator',
      'no hadith number is invented for an edition that prints none',
      row.hadith_number === null, {
        severity: 'CRITICAL',
        detail: `hadith_number=${row.hadith_number}`,
        where: 'corpus.hadiths.hadith_number',
        repro: REPRO,
      });

    // 6. encoding: no replacement characters, no control bytes, NFC-stable
    const encodingOk = !FORBIDDEN.test(row.raw_text) && row.raw_text.normalize('NFC') === row.raw_text;
    audit.check(`data.encoding:${loc}`, 'data.encoding',
      'text is valid UTF-8, NFC-stable and free of control/replacement characters',
      encodingOk, {
        severity: 'HIGH',
        detail: FORBIDDEN.test(row.raw_text) ? 'control or replacement character present' : 'text is not NFC-stable',
        where: 'corpus.hadiths.raw_text',
        repro: REPRO,
      });

    // 7. the text is Arabic scripture, not markup or a placeholder
    const arabic = (row.raw_text.match(/[؀-ۿ]/g) ?? []).length;
    audit.check(`data.shape:${loc}`, 'data.text_shape',
      'text is non-empty Arabic prose without markup',
      row.raw_text.trim().length > 0 && arabic / row.raw_text.length > 0.4 && !HTML.test(row.raw_text), {
        severity: 'HIGH',
        detail: HTML.test(row.raw_text) ? 'HTML markup in stored text' : `arabic ratio ${(arabic / Math.max(1, row.raw_text.length)).toFixed(2)}`,
        where: 'corpus.hadiths.raw_text',
        repro: REPRO,
      });

    // 8. no trace of machine-written or placeholder religious text
    audit.check(`data.no_ai:${loc}`, 'data.no_ai_generation',
      'text carries no generated/placeholder marker',
      !AI_MARKER.test(row.raw_text), {
        severity: 'CRITICAL',
        detail: `matched ${AI_MARKER.exec(row.raw_text)?.[0]}`,
        where: 'corpus.hadiths.raw_text',
        repro: REPRO,
      });

    // 9. derived fields are verbatim slices of the printed page — the parser
    //    may split the text, never rewrite, summarise or complete it.
    const derived: [string, string | null][] = [
      ['matn', row.matn], ['isnad', row.isnad], ['takhrij', row.takhrij], ['grading', row.grading],
    ];
    const rewritten = derived.filter(([, v]) => {
      const value = v?.trim();
      if (!value) return false;
      if (row.raw_text.includes(value)) return false;
      if (!idx) return true;
      // a derived field is either its own printed line or a slice of one
      if (idx.lines.has(value)) return false;
      for (const line of idx.lines) if (line.includes(value)) return false;
      return true;
    });
    audit.check(`data.derived_substring:${loc}`, 'data.no_rewrite',
      'every derived field is a verbatim slice of the printed page (nothing rephrased)',
      rewritten.length === 0, {
        severity: 'CRITICAL',
        detail: `${rewritten.map(([k]) => k).join(', ')} not found verbatim in the source`,
        where: 'src/importer/adapters/jami_kamil_shamela.ts',
        repro: REPRO,
      });

    // 10. the record is locked and not falsely marked verified
    audit.check(`data.lock_state:${loc}`, 'data.source_lock',
      'record is source_locked and only claims verification a human granted',
      row.source_locked && (row.verified || row.verification_status !== 'verified'), {
        severity: 'CRITICAL',
        detail: row.source_locked ? `verified=${row.verified} status=${row.verification_status}` : 'source_locked=false',
        where: 'corpus.hadiths',
        repro: REPRO,
      });

    // 11. dataset membership
    audit.check(`data.dataset:${loc}`, 'data.dataset',
      'record belongs to the active sealed dataset version',
      row.dataset_version === DATASET, {
        severity: 'HIGH', detail: `dataset_version=${row.dataset_version}`,
        where: 'corpus.hadiths.dataset_version', repro: REPRO,
      });

    // 12. export parity: same record, same hash, and text still withheld
    const exp = exported.get(row.id);
    audit.check(`data.export:${loc}`, 'data.export_parity',
      'exported record matches the database row and withholds text while the gate is closed',
      Boolean(exp) && exp!['content_hash'] === row.content_hash
        && exp!['source_locator'] === row.source_locator
        && exp!['raw_text'] === null, {
        severity: 'HIGH',
        detail: !exp ? 'record missing from the export' : 'hash/locator/text mismatch in the exported line',
        where: `exports/${DATASET}.jsonl`,
        repro: REPRO,
      });

    const list = hashSeen.get(row.content_hash) ?? [];
    list.push(loc);
    hashSeen.set(row.content_hash, list);
  }

  // 13. duplicates are reported, never merged away
  for (const [hash, locs] of hashSeen) {
    if (locs.length < 2) continue;
    audit.check(`data.duplicate_kept:${hash}`, 'data.duplicates',
      'repeated wording is kept as distinct records (no automatic de-duplication)',
      locs.length === new Set(locs).size, {
        severity: 'HIGH', detail: `group ${hash} lost a member`,
        where: 'corpus.hadiths', repro: REPRO,
      });
  }

  // 14. the source files themselves are unchanged since the import that
  //     recorded their hash, and each import's record count still stands.
  const imports = await query<{ file_name: string; file_hash: string; successful_records: number }>(
    `select file_name, file_hash, successful_records from corpus.raw_imports
      where status = 'completed' and file_name is not null order by file_name`,
  );
  const perVolume = new Map<number, number>();
  for (const row of rows) {
    if (row.volume_number === null) continue;
    perVolume.set(row.volume_number, (perVolume.get(row.volume_number) ?? 0) + 1);
  }
  for (const imp of imports) {
    const volume = Number(/j(\d+)\.txt$/.exec(imp.file_name)?.[1] ?? 0);
    if (!volume) continue;
    const onDisk = volumeIndex(volume).sha256;
    audit.check(`data.file_hash:${imp.file_name}`, 'data.source_files',
      'the source volume file is byte-identical to the hash recorded at import time',
      onDisk === imp.file_hash, {
        severity: 'CRITICAL',
        detail: `${imp.file_name}: on disk ${onDisk} vs recorded ${imp.file_hash}`,
        where: `${DATA_DIR}/${imp.file_name}`, repro: REPRO,
      });
    audit.check(`data.file_records:${imp.file_name}`, 'data.source_files',
      'the corpus still holds exactly the number of records that import wrote',
      perVolume.get(volume) === imp.successful_records, {
        severity: 'CRITICAL',
        detail: `volume ${volume}: ${perVolume.get(volume)} rows vs ${imp.successful_records} imported`,
        where: 'corpus.raw_imports', repro: REPRO,
      });
  }
}
